### ISSUE TITLE
Not working on Linux

### ISSUE THREAD

**Issue by jhasse** [Evpok/latex-autocomplete#1]
Hi! Somehow this package doesn't work on my machine. I'm using Ubuntu 15.10 and Atom 1.3.3. Typing in a Latex document just doesn't bring up any autocomplete. Is there anything I need to set up?

**Comment by Evpok** [comment]
Can you check the procedure I described in #2 ? (closing and reopening after session restore), it might have to do with your version of atom.

**Comment by jhasse** [comment]
I've updated to 1.4.1 and reopenend the file several times: no luck :(

**Comment by Evpok** [comment]
Weird. It works fine for me on the very same Ubuntu version. I will look into ways to find out what's happening on your machine.

**Comment by bearbin** [comment]
This issue seems to be happening to me also. I have two very similar machines and it works great on one and not at all on the other. The file is synced using dropbox, so it should be identical. I'm using atom 1.4.0 on both machines I think.

**Comment by Evpok** [comment]
Okay, I will get on with writing the tests (including activation) and ask you to run them to get a better idea of where the issue lies

**Comment by Evpok** [comment]
I have made some changes that may have fixed the issue. Could you try to reproduce?

**Comment by jhasse** [comment]
Unfortunately stilll not working for me with 0.4.2 :(

**Comment by Evpok** [comment]
I read your original post again: could it be that you are mistaken about the functions provided by this package? For now we are only autoclosing environments, this is not yet an autocompletion provider, only the first step to it. Granted, the package name is confusing.

**Comment by jhasse** [comment]
OMG, I'm sorry I've misinterpreted that. So sorry ... You're right: autoclosing environments is working fine.

**Comment by bearbin** [comment]
@Evpok the issue appears to be fixed on my end (I was using it for env closing, which wasn't working on my debian machine)

**Comment by Evpok** [comment]
Good. Next timeshard I get to work on this, I'll try to add label autocompletion, and hopefully bibliographic references after that. This way we'll be at the level of `latexer` feature-wise. Then only we'll see about macro autocompletion and so on. So... stay tuned :)
