### ISSUE TITLE
Can label autocomplete work across different files?

### ISSUE THREAD

**Issue by i-apellaniz** [Evpok/latex-autocomplete#21]
I have my work split across several files. I can imagine that this feature is feasible ¡, but maybe is too difficult to implement.

I open the issue, just to have one related to this. A similar issue is the #15

**Comment by hesstobi** [comment]
I have created a separate package for this: https://github.com/hesstobi/atom-autocomplete-latex-references. Feel free to integrate this in your package or give a note to use this for references.

**Comment by Evpok** [comment]
@hesstobi Thank you for that ! I do intend to add these functions to this package, but for want of time, have not done so yet.

In the meantime, though, I would be happy to advertise your packages. I'll link to them in the README as soon as I get hold of a computer. As for including them, it doesn't seem likely if they are not decaffeinated, as I don't trust myself enough to add coffeescript to latex-autocomplete codebase :)
