### ISSUE TITLE
incompatible with autocomplete-bibtex

### ISSUE THREAD

**Issue by leobrowning92** [Evpok/latex-autocomplete#25]
When I enable both latex-autocomplete and autocomplete-bibtex only the bibtex autocomplete functions in a tex file. 

Clarification: when typing `@b` , which is the way to prompt for the bibtex autocomplete, it will prompt for `\begin{env}  ...  \end{env}` , as well as the bibtex prompt. If I type `beg` there is no prompt for `\begin{env}  ...  \end{env}` which would be the standard behaviour for just latex-autocomplete

Can someone please suggest how I can debug this or how I can provide more information for this issue so that it can be resolved?

**Comment by Evpok** [comment]
Hello, I don't use `autocomplete-bibtex`, but according to its README

> By default, the autocomplete-bibtex package is configured to provide suggestions in scopes which Atom recognizes as Markdown.

Whereas `latex-autocomplete` provides autocompletion in LaTeX scopes. So I am not sure what you are trying to do here.

**Comment by leobrowning92** [comment]
Hi, I should clarify. I have edited the scope of autocomplete-bibtex to include `.text.tex.latex` in order for the autocomplete to occur while writting a text document, as suggested in their README.

The issue is then that the @ prompt (which is the standard usage for autocomplete bibtex) is being required to access the latex-autocomplete while in a latex scope.

I would be happy to use another package that allows bibtex citation. Do you know if the latexer package plays nicely with autocomplete-latex, as it looks like it also has that functionality?

**Comment by Evpok** [comment]
I think I see what you are asking, but you are knocking at the wrong door : `\begin{env}…\end{env}` autocompletion in latex scopes is not provided by latex-autocomplete, but by language-latex snippets, so your issue might be with autocomplete-snippets.

Still, I'd suggest providing them a screenshot of your issue, because I am still not sure of what your problem is.
