### ISSUE TITLE
Specifying external macros file stopped working in v1.1.0

### ISSUE THREAD

**Issue by raulpardo** [Evpok/latex-autocomplete#28]
After the latest update specifying a macro file always throws an exception.

In this line

https://github.com/Evpok/latex-autocomplete/blob/516d1cff13b44ec307804fdf3a0817135fcfe078/lib/macros_autocompletion/macro_completer.js#L55

`match[0]` should be `match[1]` to only get the file name. However, after changing this, the call to the function `readFile()` in the following line still throws an exception (even though the path is correct) 

https://github.com/Evpok/latex-autocomplete/blob/516d1cff13b44ec307804fdf3a0817135fcfe078/lib/macros_autocompletion/macro_completer.js#L58

Any ideas why?

**Comment by Evpok** [comment]
Yes, mostly because I am an idiot. I found the error, currently fixing it.

**Comment by Evpok** [comment]
Fixed by 4bd5e98f95f0ea834ee86852294bd321e0baa699 (at least WORKSFORME)

Btw, if you had time to write tests for that functionality, that would be greatly appreciated ;)

**Comment by raulpardo** [comment]
I've written a simple test to check it, see #30
