### ISSUE TITLE
Multiple \begin's in one line

### ISSUE THREAD

**Issue by 314eter** [Evpok/latex-autocomplete#3]
There are several issues.

1. Environments are closed in the wrong order.
2. \end macros are joined with commas.
3. \item's are joined with commas.

Example:
```latex
\begin{env}\begin{itemize}
    ,\item 
\end{env},\end{itemize}
```

**Comment by 314eter** [comment]
Another problem:

```latex
\begin{env}\begin{env}\end{env}
    
\end{env}\end{env}
```

**Comment by Evpok** [comment]
Thanks for reporting, I should have tested that (and found time to write the spec…). Working on it.

**Comment by Evpok** [comment]
First (the easy) issue fixed. The second might take more thinking
