### ISSUE TITLE
Nested itemizes on one line

### ISSUE THREAD

**Issue by 314eter** [Evpok/latex-autocomplete#5]
When multiple itemizes are opened, multiple items are inserted.
```latex
\begin{itemize}\item\begin{itemize}
  \item \item
\end{itemize}\end{itemize}
```
I think it's never necessary to insert more than one item. Just looking at the last opened environment and inserting one item if necessary should suffice. The only problem would be:
```latex
\begin{itemize}\item
  \item
\end{itemize}
```

**Comment by Evpok** [comment]
Indeed, I saw it in your PR, just forgot to add it.

**Comment by 314eter** [comment]
Ok, thanks ;) The second example is still not fixed, that requires checking for items on the same line, but I don't think it's necessary to spend time on it.
