### ISSUE TITLE
Autocomplete on last line

### ISSUE THREAD

**Issue by 314eter** [Evpok/latex-autocomplete#6]
When autocompleting the last line of a document:
```latex
\begin{env} % cursor was here
\end{env}
% jumps to here
```

With itemize:
```latex
\begin{itemize} % cursor was here
  \item \end{itemize}
% jumps to here
```

**Comment by Evpok** [comment]
I don't have this issue, but when I try to autocomplete in the last line, the autocomplete is actually triggered twice (with funky consequences). Looking into this.

**Comment by Evpok** [comment]
Btw are you on some kind of holy crusade? I see you filed similar issues on `latexer`. No complaining, though, nice to see this is useful enough that you took the time to report those :)

**Comment by Evpok** [comment]
Not so pleased with how I dealed with the cursor position, though

**Comment by 314eter** [comment]
It's fixed :+1:

I was using `latexer`, when I found a really annoying bug, so I reported and fixed it. Then I found some more problems, that were more difficult, so I switched to `latex-autocomplete`. My crusade is over now. :wink:
